- name: "[Authentication]: authenticate gcloud service account"
  shell: gcloud auth activate-service-account --key-file=/tmp/cloud_config.yml

- name: "[Authentication]: Setting the project ID in the gcloud"
  shell: gcloud config set project {{ project_id }}

- name: "[Authentication]: Checking gcloud config list"
  shell: gcloud config list