---

## Following variables requierd to perform action on AWS instance using chaostoolkit, chaostoolkit-aws driver
LABEL_NAME: "app" # label name
NAME_SPACE: "default" # name space
APP_ENDPOINT: "localhost" ## you define ingress or service endpoint
chaos_prob: "application-must-respond-normally" ## chaos probe validation
chaos_action: "kill_microservice"    ## stop_instance,
chaos_experiment: "k8-service-kill"    ## stop_instance,
PERCENTAGE: "100" ## percentage pod to be terminated
REPORT: "false"  ## type of report coming from experiment
REPORT_ENDPOINT: "none" # kafka or http endpoint which accept the json response body
file: service-kill-health.j2 ## pod-app-kill-count.j2 (To terminate pod on k8)
