---
apiVersion: v1
kind: Pod
metadata:
  name: stopinstance
spec:
  containers:
  - name: kubernetes-job
    image: openebs/tests-chaostoolkit
    imagePullPolicy: Always
    command: ["chaos", "run", "/node_chaos_aws.json"]
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /node_chaos_aws.json
      subPath: node_chaos_aws.json
      name: chaos-instance-config
  volumes:
    - name: chaos-instance-config
      configMap:
        name: chaosec2instance
  restartPolicy: Never