---
# This workflow is to perform automatic release on litmus-ansible repository
# Please provide the release version and release tag in github secrets for the upcoming release.
name: AutoRelease

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tag:
        description: 'Release tag'
        required: true
      branch:
        description: 'Release branch name'
        required: true

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:

      # create a release branch from master
      # Provide release branch from the github secret ex. 1.9.x
      - uses: peterjgrainger/action-create-branch@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: '${{ github.event.inputs.branch }}'

      # Provide release tag from the github secret ex. 1.9.0
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.tag }}"
          prerelease: false
          title: "${{ github.event.inputs.tag }}"
