---
name: Push
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

env:
  DOCKER_REPO: litmuschaos
  DOCKER_IMAGE: ansible-runner
  DOCKER_TAG: ci

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: checking dependencies are installed
        run: make deps

      - name: Running ansible syntax-checks
        run: make syntax-checks

      - name: Running ansible lint-checks
        run: make lint-checks

  push:
    needs: pre-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DNAME }}
          password: ${{ secrets.DPASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: build/ansible-runner/Dockerfile
          platforms: linux/amd64
          tags: litmuschaos/ansible-runner:ci